merge-key: "nroc4/nroc4/nmasapp"

ibm_mas_suite_configs:
  - mas_config_name: "nmasapp-sls-system"
    mas_config_chart: ibm-mas-sls-config
    mas_config_scope: system
    mas_workspace_id:
    mas_application_id:
    mas_config_kind: "slscfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    registration_key: "<path:secret/data/nroc4/nroc4/nmasapp/sls#registration_key>"
    url: "<path:secret/data/nroc4/nroc4/nmasapp/sls#url>"
    ca:
      crt: "<path:secret/data/nroc4/nroc4/nmasapp/sls#ca.crt>"

  - mas_config_name: "nmasapp-bas-system"
    mas_config_chart: ibm-mas-bas-config
    mas_config_scope: system
    mas_workspace_id:
    mas_application_id:
    mas_config_kind: "bascfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    dro_endpoint_url: "<path:secret/data/nroc4/nroc4/dro#url>"
    dro_contact:
      email: "Najeeb.Mehboob@spireenergy.com"
      first_name: "Najeeb"
      last_name: "Mehboob"
    dro_api_token: "<path:secret/data/nroc4/nroc4/dro#api_token>"
    dro_ca:
      crt: "<path:secret/data/nroc4/nroc4/dro#ca.crt>"

  - mas_config_name: "nmasapp-mongo-system"
    mas_config_chart: ibm-mas-mongo-config
    mas_config_scope: system
    mas_workspace_id:
    mas_application_id:
    mas_config_kind: "mongocfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    username: "<path:secret/data/nroc4/nroc4/nmasapp/mongo#username>"
    password: "<path:secret/data/nroc4/nroc4/nmasapp/mongo#password>"
    config:
      hosts:
        - host: "<path:secret/data/nroc4/nroc4/nmasapp/mongo#host>"
          port: 27017
      configDb: admin
      authMechanism: DEFAULT
      retryWrites: false
      credentials:
        secretName: "system-mongo-credentials"
    certificates:
      - alias: ca
        crt: "<path:secret/data/nroc4/nroc4/nmasapp/mongo#ca.crt>"

  - mas_config_name: "nmasapp-jdbc-system"
    mas_config_chart: ibm-jdbc-config
    mas_config_scope: system
    mas_workspace_id:
    mas_application_id:
    mas_config_kind: "jdbccfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    jdbc_type: external
    jdbc_instance_name: oracle
    jdbc_instance_username: "<path:secret/data/nroc4/nroc4/nmasapp/jdbc-system#username>"
    jdbc_instance_password: "<path:secret/data/nroc4/nroc4/nmasapp/jdbc-system#password>"
    jdbc_connection_url: "<path:secret/data/nroc4/nroc4/nmasapp/jdbc-system#jdbc_url>"
    jdbc_ssl_enabled: false
    system_suite_jdbccfg_labels:
      mas.ibm.com/configScope: system
      mas.ibm.com/instanceId: nmasapp
